### ISSUE TITLE
Add Fiducials

### ISSUE THREAD

**Issue by G-Pereira** [tigard-tools/tigard#35]
Hello! Really nice project! I would like to suggest adding 3 non-collinear fiducials (3 corners of the board) so a pick and place like the Index (https://github.com/sphawes/index) can be used to assemble these boards.

**Comment by fharding1** [comment]
When the boards were manufactured I believe we just put fiducial markings on the panel edge rails. Also, different manufacturers often have different requirements/expectations for fiducials. I'm not sure it makes sense to add them to master.

**Comment by G-Pereira** [comment]
I've meant fiducials on the board itself so people can assemble at shops or at home. I would imagine you would like to do that as well so decrease manufacturing costs and increase sales and profit

**Comment by fharding1** [comment]
If we are doing a large run, sending gerbers with fiducial markings would be unnecessary and potentially confuse the manufacturer. If the manufacturer is handling panelization, they will want to have control over the size/shape/position of the fiducials.

Fiducial markings are not necessary for hand assembly.

If someone does have a home pick and place machine, and happens to be assembling just one board instead of a panel, I would imagine they have the ability to add fiducial markings themselves (and to their liking).

**Comment by G-Pereira** [comment]
Fair enough!

**Comment by securelyfitz** [comment]
Just wanted to add - we optimized tigard for mass production and automated assembly, in contrast to [TIMEP](https://github.com/Matir/timep) which is very similar and optimized for hand assembly. Small batch automated assembly falls into a gap between the two, but I agree with @fharding1 that since fiducial requirements vary based on your assembly method, it's best to keep it out of the board design itself.

**Comment by G-Pereira** [comment]
Me too, that's a very valid point!
