### ISSUE TITLE
Configuring for FT245 FIFO mode

### ISSUE THREAD

**Issue by svanimisetti** [tigard-tools/tigard#60]
Tigard is an amazing project - and I am planning to purchase it soon from CrowdSupply.

How can I configure Tigard for FT245 using the EEPROM. From the documentation, I did not find enough information on how to set configuration parameters on the EEPROM to enable "not-the-usual" programming modes? From Table 4.11 on Page 46 of the [datasheet](http://www.ftdichip.com/Support/Documents/DataSheets/ICs/DS_FT2232H.pdf), FT245 has both sync/async modes. I would appreciate if you can share documentation which show how I can use [FT_Prog](https://ftdichip.com/wp-content/uploads/2020/08/AN_124_User_Guide_For_FT_PROG.pdf) utility to set the configuration parameters on Tigard by myself.

Thanks in advance!

**Comment by securelyfitz** [comment]
There's no way to use tigard in 245 mode without hardware modifications. That mode expects to use several pins as bidirectional I/O, but all the pins are hardwired to unidirectional level shifters to properly support UART, SPI, JTAG, I2C, and SWD.

If you do want to explore the additional modes, I've attached the [tigard-eeprom.conf](https://github.com/tigard-tools/tigard/files/10355433/tigard-eeprom.txt) which is used when programming the eeprom in production. The actual serial number is put in place of the x's and then it's flashed on a linux system using:
```
ftdi_eeprom  --flash-eeprom tigard-eeprom.conf
```
Similar settings should be possible with FT_Prog, but i haven't used it. You should be able to use it to read out the firmware and see how it's configured, and set the settings you're interested in.

Since 245 mode isn't possible, I'm going to close this issue as can't fix, but let me know if you have any additional questions.
