### ISSUE TITLE
R22

### ISSUE THREAD

**Issue by fy2002** [tigard-tools/tigard#62]
![image](https://github.com/tigard-tools/tigard/assets/71111861/19d3190d-63bb-4dd3-a8d1-33f9a8e66a10)
 what is resistor r22 2k2 for? It seems that net BD7 connected to nothing.

**Comment by securelyfitz** [comment]
That's for using iceprog to progam ice40 fpgas. It uses the BDBUS7 as the ICE_CRESET  output and does not use BDBUS5 at all. Since we're limited on output pins and already have BDBUS5 as jtag/swd reset, we tie them together with the 2k2 resistor so that BD7 only affects the output when BD5 is high-z. See #15
